version: '3.8'

services:
  jrtb-db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: 'jrtb_db'
      MYSQL_USER: 'vaseba'
      MYSQL_PASSWORD: 'dfkbrj'
      MYSQL_ROOT_PASSWORD: 'dfkbrj'
    ports:
      - '3307:3306'
    expose:
      - '3307'